#!/usr/bin/env python2.7
# (C) British Crown Copyright 2010 - 2013, Met Office
#
# This file is part of Iris.
#
# Iris is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Iris is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Iris.  If not, see <http://www.gnu.org/licenses/>.
"""A script to build a standalone runnable 'make_shapefiles' script."""

import argparse
import datetime
import os.path
import shutil

parser = argparse.ArgumentParser(
    description="Build the 'make_shapefiles' script.")
parser.add_argument('outfile', nargs='?', default=None,
                    help=('path to output file or directory. '
                          'Default = <install>/tools'))
parser.add_argument('-y', '--dryrun', action='store_true',
                    help="don't perform actual actions")
parser.add_argument('-v', '--verbose', action='store_true',
                    help="print extra messages")

args = parser.parse_args()

do_dryrun = args.dryrun
do_verbose = args.verbose

import iris
iris_module_dir = os.path.dirname(iris.__file__)
iris_base_dir = os.path.join('/', *iris_module_dir.split('/')[:-2])
tools_dir_path = os.path.join(iris_base_dir, 'tools')
make_shapefiles_filepath = os.path.join(tools_dir_path, 'make_shapefiles.py')
shapefiles_module_filepath = os.path.join(
    iris_base_dir, 'lib', 'iris', 'experimental', 'shapefiles.py')

out_path = args.outfile
if out_path:
    if os.path.isdir(out_path):
        out_path = os.path.join(out_path, 'make_shapefiles')
else:
    out_path = os.path.join(tools_dir_path, 'make_shapefiles')

if do_dryrun and do_verbose:
    print '(Dry run : no actual operations will be performed.)'

if do_verbose:
    print 'Creating file : ', out_path

with open(out_path, 'w') as out_file:
    if do_verbose:
        print 'Write shebang..'
    if not do_dryrun:
        out_file.write('#!/usr/bin/env python2.7\n')
    if do_verbose:
        print 'Write topnotes..'
    if not do_dryrun:
        out_file.write('#\n')
        out_file.write('# This File automatically generated by Iris utility'
                       ' : "{}"\n'.format(os.path.basename(__file__)))
        out_file.write('# Iris version'
                       ' : "{}"\n'.format(iris.__version__))
        out_file.write('# Date'
                       ' : "{}"\n'.format(str(datetime.datetime.now())))
        out_file.write('#\n')
    if do_verbose:
        print 'Add shapefiles module from "{}" ..'.format(
            shapefiles_module_filepath)
    if not do_dryrun:
        out_file.write('\n')
        with open(shapefiles_module_filepath) as f_in:
            out_file.writelines(f_in.readlines())
    if do_verbose:
        print 'Add make_shapefiles script from "{}" ..'.format(
            make_shapefiles_filepath)
    if not do_dryrun:
        out_file.write('\n')
        with open(make_shapefiles_filepath) as f_in:
            out_file.writelines(f_in.readlines())

if do_verbose:
    print 'Make runnable..'
    os.chmod(out_path, mode)

if do_verbose:
    print 'All Done.'
