# Copyright Iris contributors
#
# This file is part of Iris and is released under the BSD license.
# See LICENSE in the root of the repository for full licensing details.

# Handy default options for the run_doctests tool, specific to Iris usage.

[tool.run-doctests]
default-args = {"verbose" = 1, "optionflags" = 12}  # NORMALISE_WHITESPACE | ELLIPSIS

[tool.run-doctests.modules]
default-args = {"publiconly" = 1, "recurse" = 1}
add-excludes = [
    "geovista",
    "iris.tests",
    "iris._version",
]

[tool.run-doctests.docs]
add-excludes = [
    "docs/src/generated",
    "docs/src/whatsnew",
]
